version: '3.9'
services:
  parser:
    container_name: parser
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: